networking_init_cms_default:
    path: /
    defaults: {_controller: NetworkingInitCmsBundle:FrontendPage:home}

networking_init_cms_home:
    path: /
    defaults: {_controller: NetworkingInitCmsBundle:FrontendPage:home}

networking_init_cms_admin:
    path: /admin/
    defaults: {_controller: NetworkingInitCmsBundle:FrontendPage:admin}

networking_init_cms_admin_security_login:
    path: /admin/login
    defaults: { _controller: NetworkingInitCmsBundle:AdminSecurity:login }

networking_init_cms_admin_security_check:
    path: /admin/login_check
    defaults: { _controller: NetworkingInitCmsBundle:AdminSecurity:check }
    methods: [POST]

networking_init_cms_admin_security_logout:
    path: /admin/logout
    defaults: { _controller: NetworkingInitCmsBundle:AdminSecurity:logout }

networking_init_cms_admin_resetting_request:
    path: /admin/request
    defaults: { _controller: NetworkingInitCmsBundle:AdminResetting:request }
    methods: [GET]

networking_init_cms_admin_resetting_send_email:
    path: /admin/send-email
    defaults: { _controller: NetworkingInitCmsBundle:AdminResetting:sendEmail }
    methods: [POST]

networking_init_cms_admin_resetting_check_email:
    path: /admin/check-email
    defaults: { _controller: NetworkingInitCmsBundle:AdminResetting:checkEmail }
    methods: [GET]

networking_init_cms_admin_resetting_reset:
    path: /admin/reset/{token}
    defaults: { _controller: NetworkingInitCmsBundle:AdminResetting:reset }
    methods: [GET|POST]

networking_init_change_admin_language:
    path: /change_admin_language/{locale}
    defaults: {_controller: NetworkingInitCmsBundle:FrontendPage:changeAdminLanguage}
    methods: [GET|POST]
    requirements:
        locale: .+

networking_init_change_language:
    path: /change_language/{oldLocale}/{locale}
    defaults: {_controller: NetworkingInitCmsBundle:FrontendPage:changeLanguage}
    methods: [GET|POST]
    requirements:
        locale: .+

networking_init_view_draft:
    path: /view_draft/{locale}/{path}
    defaults: {_controller: NetworkingInitCmsBundle:FrontendPage:viewDraft}
    requirements:
        locale: (.*)?
        path: (.*)?

networking_init_view_draft_no_param:
    path: /view_draft
    defaults: {_controller: NetworkingInitCmsBundle:FrontendPage:viewDraft}

networking_init_view_live:
    path: /view_live/{locale}/{path}
    defaults: {_controller: NetworkingInitCmsBundle:FrontendPage:viewLive}
    requirements:
        locale: (.*)?
        path: (.*)?

networking_init_view_live_no_param:
    path: /view_live
    defaults: {_controller: NetworkingInitCmsBundle:FrontendPage:viewLive}

networking_init_cms_help:
    path: /admin/help/{adminCode}/{action}
    defaults: {_controller: NetworkingInitCmsBundle:HelpText:adminHelp}
    requirements:
        adminCode: .+
        action: (.*)?

networking_init_cms_help_dashboard:
    path: /admin/help/{adminCode}
    defaults: {_controller: NetworkingInitCmsBundle:HelpText:adminHelp}
    requirements:
        adminCode: .+

networking_init_cms_file_download:
    path: /file/download/{id}/{name}
    defaults: { _controller: SonataMediaBundle:Media:download, format: 'reference' }
    requirements:
        name: (.*)?
        format: (.*)?

networking_init_cms_image_view:
    path: /image/view/{id}/{format}/{name}
    defaults: { _controller: NetworkingInitCmsBundle:Media:viewImage, format: 'reference' }
    requirements:
        name: (.*)?
        format: (.*)?

networking_init_cms_clear_cache:
    path: /cache/clear
    defaults: { _controller: NetworkingInitCmsBundle:Cache:clear }

initcms_no_translation:
    path: /no_translation
    defaults: {_controller: NetworkingInitCmsBundle:FrontendPage:translationNotFound}

initcms_404:
    path: /404
    defaults: {_controller: NetworkingInitCmsBundle:FrontendPage:pageNotFound}

xml_sitemap:
    path: /xml_sitemap/{locale}
    defaults: {_controller: NetworkingInitCmsBundle:Xml:sitemap, locale: ''}
    requirements:
    methods: GET

_configure_cms:
    path: /cms_install
    defaults: {_controller: NetworkingInitCmsBundle:InitCmsInstall:index}

_welcome_cms:
    path: /welcome
    defaults: {_controller: NetworkingInitCmsBundle:InitCmsInstall:index}

_install_db:
    path: /install_db/{complete}
    defaults: {_controller: NetworkingInitCmsBundle:InitCmsInstall:installDb, complete: 0}
    requirements:
        complete: /d+

_initcms_admin_navbar:
    path: '/admin/_initcms_admin_navbar/{page_id}'
    defaults: { _controller: NetworkingInitCmsBundle:FrontendPage:adminNavbar }

networking_init_cms_set_admin_portal_width:
    path: /admin/set_admin_portal_width
    defaults: { _controller: NetworkingInitCmsBundle:CmsHelper:setAdminPortalWidth }

networking_init_cms_admin_login:
    path: /admin/login{trailingSlash}
    defaults:
      _controller: FrameworkBundle:Redirect:urlRedirect
      path: /admin/
      permanent: true
    requirements: { trailingSlash : "[/]{1}" }





