sonata_media:
    class:
        media:              Networking\InitCmsBundle\Entity\Media
        gallery:            Networking\InitCmsBundle\Entity\Gallery
        gallery_has_media:  Networking\InitCmsBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb
    contexts:
        default:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.youtube

            formats:
                small: { width: 100 , quality: 70}
                medium: { width: 400, height: 300 , quality: 70}
                big:   { width: 800, quality: 70}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false

#    providers:
#        image:
#            resizer: sonata.media.resizer.square

